### ISSUE TITLE
Amplitude+LearnDash Analytics

### ISSUE THREAD

**Issue by NatalyaMetlitskaya** [zumba/amplitude-php#24]
Hello!

I have a website on WordPress with LMS LearnDash.

I need to set following analytics: https://prnt.sc/t5h7nx
Is it possible? How can I do it?

**Comment by jonyo** [comment]
Sorry for the late reply, I had notifications off for this project...

I am not familiar with LMS LearnDash, but if you just need to send an event to amplitude using PHP, then you should be able to use this library.  This is meant to be used by developers, it is not something you can just "drop in" like a WP plugin or something.

If you are familiar with PHP, there are a lot of code examples on the main readme for the project.  Or you can possibly hire someone to add it if you are not familiar with PHP.

That said, the library has not been updated in a while and apparently there is a newer version of the amplitude API.  It should continue to work until amplitude completely closes down the old version (or if someone has the time to update this library).
